[package]
name = "enceladus"
version = "0.0.1"
authors = ["Jack McPherson <jack.mcpherson12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

